name: build our image

on:
  push:
    branches: master
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag $DOCKER_USER/$REPO_NAME:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .